package responses

// StreamEventType 表示 Responses 流式事件类型。
type StreamEventType string

const (
	StreamEventAudioDelta                      StreamEventType = "response.audio.delta"
	StreamEventAudioDone                       StreamEventType = "response.audio.done"
	StreamEventAudioTranscriptDelta            StreamEventType = "response.audio.transcript.delta"
	StreamEventAudioTranscriptDone             StreamEventType = "response.audio.transcript.done"
	StreamEventCodeInterpreterCallCodeDelta    StreamEventType = "response.code_interpreter_call_code.delta"
	StreamEventCodeInterpreterCallCodeDone     StreamEventType = "response.code_interpreter_call_code.done"
	StreamEventCodeInterpreterCallCompleted    StreamEventType = "response.code_interpreter_call.completed"
	StreamEventCodeInterpreterCallInProgress   StreamEventType = "response.code_interpreter_call.in_progress"
	StreamEventCodeInterpreterCallInterpreting StreamEventType = "response.code_interpreter_call.interpreting"
	StreamEventCompleted                       StreamEventType = "response.completed"
	StreamEventContentPartAdded                StreamEventType = "response.content_part.added"
	StreamEventContentPartDone                 StreamEventType = "response.content_part.done"
	StreamEventCreated                         StreamEventType = "response.created"
	StreamEventError                           StreamEventType = "error"
	StreamEventFileSearchCallCompleted         StreamEventType = "response.file_search_call.completed"
	StreamEventFileSearchCallInProgress        StreamEventType = "response.file_search_call.in_progress"
	StreamEventFileSearchCallSearching         StreamEventType = "response.file_search_call.searching"
	StreamEventFunctionCallArgumentsDelta      StreamEventType = "response.function_call_arguments.delta"
	StreamEventFunctionCallArgumentsDone       StreamEventType = "response.function_call_arguments.done"
	StreamEventInProgress                      StreamEventType = "response.in_progress"
	StreamEventFailed                          StreamEventType = "response.failed"
	StreamEventIncomplete                      StreamEventType = "response.incomplete"
	StreamEventOutputItemAdded                 StreamEventType = "response.output_item.added"
	StreamEventOutputItemDone                  StreamEventType = "response.output_item.done"
	StreamEventReasoningSummaryPartAdded       StreamEventType = "response.reasoning_summary_part.added"
	StreamEventReasoningSummaryPartDone        StreamEventType = "response.reasoning_summary_part.done"
	StreamEventReasoningSummaryTextDelta       StreamEventType = "response.reasoning_summary_text.delta"
	StreamEventReasoningSummaryTextDone        StreamEventType = "response.reasoning_summary_text.done"
	StreamEventReasoningTextDelta              StreamEventType = "response.reasoning_text.delta"
	StreamEventReasoningTextDone               StreamEventType = "response.reasoning_text.done"
	StreamEventRefusalDelta                    StreamEventType = "response.refusal.delta"
	StreamEventRefusalDone                     StreamEventType = "response.refusal.done"
	StreamEventOutputTextDelta                 StreamEventType = "response.output_text.delta"
	StreamEventOutputTextDone                  StreamEventType = "response.output_text.done"
	StreamEventWebSearchCallCompleted          StreamEventType = "response.web_search_call.completed"
	StreamEventWebSearchCallInProgress         StreamEventType = "response.web_search_call.in_progress"
	StreamEventWebSearchCallSearching          StreamEventType = "response.web_search_call.searching"
	StreamEventImageGenCallCompleted           StreamEventType = "response.image_generation_call.completed"
	StreamEventImageGenCallGenerating          StreamEventType = "response.image_generation_call.generating"
	StreamEventImageGenCallInProgress          StreamEventType = "response.image_generation_call.in_progress"
	StreamEventImageGenCallPartialImage        StreamEventType = "response.image_generation_call.partial_image"
	StreamEventMCPCallArgumentsDelta           StreamEventType = "response.mcp_call_arguments.delta"
	StreamEventMCPCallArgumentsDone            StreamEventType = "response.mcp_call_arguments.done"
	StreamEventMCPCallCompleted                StreamEventType = "response.mcp_call.completed"
	StreamEventMCPCallFailed                   StreamEventType = "response.mcp_call.failed"
	StreamEventMCPCallInProgress               StreamEventType = "response.mcp_call.in_progress"
	StreamEventMCPListToolsCompleted           StreamEventType = "response.mcp_list_tools.completed"
	StreamEventMCPListToolsFailed              StreamEventType = "response.mcp_list_tools.failed"
	StreamEventMCPListToolsInProgress          StreamEventType = "response.mcp_list_tools.in_progress"
	StreamEventOutputTextAnnotationAdded       StreamEventType = "response.output_text.annotation.added"
	StreamEventQueued                          StreamEventType = "response.queued"
	StreamEventCustomToolCallInputDelta        StreamEventType = "response.custom_tool_call_input.delta"
	StreamEventCustomToolCallInputDone         StreamEventType = "response.custom_tool_call_input.done"
	StreamEventKeepalive                       StreamEventType = "keepalive"
)
